export const ROUTES = {
    TABS: 'TABS',
    HOME: 'HOME',
    CREATE: 'CREATE',
    SETTINGS: 'SETTINGS',
    STATUS_BIO_DETAIL: 'STATUS_BIO_DETAIL',
    GENERATE_CONTENT: 'GENERATE_CONTENT',
    ABOUT: 'ABOUT',
    ACCOUNT_SYNC: 'ACCOUNT_SYNC',
    DONATE: 'DONATE',
} as const