export const STORAGE_KEYS = {
    THEME: 'APP_THEME',
    GENERATED_LIST: 'GENERATED_LIST',
    LANGUAGE: 'LANGUAGE',
    USER: 'USER',
    LAST_SYNC_TIME: 'LAST_SYNC_TIME',
    IMAGE_USED_DATE: 'IMAGE_USED_DATE',
    GENERATE_COUNT: 'GENERATE_COUNT',
    GENERATE_DATE: 'GENERATE_DATE',
}